---
abstract: 'Fast, Streaming, and Searchable JSON decoder.'
author:
  - 'M. Nunberg <mnunberg@haskalah.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: JSON-SL
no_index:
  directory:
    - t
    - inc
requires:
  Constant::Generate: 0.16
  Test::More: 0
resources:
  repository: https://github.com/mnunberg/perl-JSON-SL/
version: 0.0_5
